service: aws-price-fetcher

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  deploymentBucket:
    name: price-fetcher-serverlessdeploymentbucket
  iam:
    role: arn:aws:iam::008735640664:role/Price-Notifier-Role

functions:
  price_fetcher:
    handler: handler.price_fetcher
    description: Fetches gasoline price from public API
    timeout: 30
  price_publisher:
    handler: handler.price_publisher
    description: Publish gasoline drops
    timeout: 30

custom:
  pythonRequirements:
    useDownloadCache: false
    useStaticCache: false
    slim: true
    slimPatternsAppendDefaults: false
    slimPatterns:
      - "**/*.py[c|o]"
      - "**/__pycache__*"

plugins:
  - serverless-python-requirements
